In [53]:
import numpy as np
print(np.__version__)


2.2.5


In [54]:
import numpy as np

arr_ = np.array([101, 201, 301, 401, 501])

print(arr_)           
print(type(arr_))     


[101 201 301 401 501]
<class 'numpy.ndarray'>


In [55]:
import numpy as np

nameList = ['Angel', "Shemi", "Marvel", "Linda"]
ageTuple = (41, 32, 21, 19)
gradeDict = {"CSC102": 89, "MTH 102": 77, "CHM 102": 69, "GST 102": 99}

arr_nameList = np.array(nameList)
arr_ageTuple = np.array(ageTuple)
arr_gradeDict = np.array(list(gradeDict.items()))  # Convert dict to list of tuples for array

print(arr_nameList)
print(arr_ageTuple)
print(arr_gradeDict)


['Angel' 'Shemi' 'Marvel' 'Linda']
[41 32 21 19]
[['CSC102' '89']
 ['MTH 102' '77']
 ['CHM 102' '69']
 ['GST 102' '99']]


In [ ]:
import numpy as np

classNum = int(input("How many students are in the CSC 102 class?"))

if classNum == 1:
    print("There is only", classNum, "student in CSC 102 class")
else:
    print("There are", classNum, "students in CSC 102 class")


In [57]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [58]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)


[[1 2 3]
 [4 5 6]]


In [59]:
import numpy as np

arr = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[1, 2, 3], [4, 5, 6]],
    [[1, 2, 3], [4, 5, 6]]
])

print(arr)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [60]:
import numpy as np

a = np.array(42)  # 0-D array
b = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])  # 3-D array
c = np.array([[1, 2, 3], [4, 5, 6]])  # 2-D array
d = np.array([1, 2, 3, 4, 5])  # 1-D array

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
3
2
1


In [61]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=8)

print(arr)
print('Number of dimensions:', arr.ndim)


[[[[[[[[1 2 3 4]]]]]]]]
Number of dimensions: 8


In [62]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [63]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [64]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [65]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [66]:
# Slice elements from index 1 to index 5 from the following array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [67]:
# Slice elements from index 4 to the end of the array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [68]:
# Slice elements from the beginning to index 4 (not included):

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [69]:
import numpy as np

int_arr = np.array([1, 2, 3, 4])
str_arr = np.array(['apple', 'banana', 'cherry'])

print(int_arr.dtype)
print(str_arr.dtype)


int64
<U6


In [70]:
#Iterate on each scalar element of the 2-D array:
    
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y,x)

1 [1 2 3]
2 [1 2 3]
3 [1 2 3]
4 [4 5 6]
5 [4 5 6]
6 [4 5 6]


In [71]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    print(x[0][1])  
    print(x[1][0]) 


2
4
8
10


In [72]:
# Join two arrays

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [73]:
# Join two arrays

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [74]:
# Access splitted arrays

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [75]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
